/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stmik.PengolahNilai_UAS;

import java.awt.Label;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author DELL
 */
public class FormNilaiSTMIK extends javax.swing.JFrame {

    /**
     * Creates new form FormNilaiSTMIK
     */
    public FormNilaiSTMIK() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelnamaApps = new javax.swing.JLabel();
        label1Hitung1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInput1 = new javax.swing.JTable();
        labelTugas1 = new java.awt.Label();
        labelUTS1 = new java.awt.Label();
        labelUAS1 = new java.awt.Label();
        jComboBoxTugas1 = new javax.swing.JComboBox();
        jComboBoxUTS1 = new javax.swing.JComboBox();
        jComboBoxUAS1 = new javax.swing.JComboBox();
        jButtonStatistic = new javax.swing.JButton();
        jButtonekspor1 = new javax.swing.JButton();
        jTextFieldLoad = new javax.swing.JTextField();
        jButtonBrowse1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile1 = new javax.swing.JMenu();
        jMenuEdit1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Aplikasi Pengolah Nilai"); // NOI18N

        jLabelnamaApps.setBackground(new java.awt.Color(102, 255, 204));
        jLabelnamaApps.setFont(new java.awt.Font("Footlight MT Light", 1, 11)); // NOI18N
        jLabelnamaApps.setForeground(new java.awt.Color(51, 0, 255));
        jLabelnamaApps.setText("Aplikasi Pengolah Nilai");

        label1Hitung1.setName(""); // NOI18N
        label1Hitung1.setText("Hitung Nilai Akhir");

        jTableInput1.setBackground(new java.awt.Color(204, 255, 255));
        jTableInput1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "NPM", "Tugas", "UTS", "UAS", "Nilai Akhir"
            }
        ));
        jScrollPane1.setViewportView(jTableInput1);

        labelTugas1.setName(""); // NOI18N
        labelTugas1.setText("Presentasi Tugas");

        labelUTS1.setName(""); // NOI18N
        labelUTS1.setText("Prsentasi UTS");

        labelUAS1.setName(""); // NOI18N
        labelUAS1.setText("Presentasi UAS");

        jComboBoxTugas1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "20", "30", "50" }));

        jComboBoxUTS1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "20", "30", "50" }));

        jComboBoxUAS1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "30", "40", "50" }));

        jButtonStatistic.setText("Statistic");

        jButtonekspor1.setText("Ekspor");

        jTextFieldLoad.setEditable(false);
        jTextFieldLoad.setText("Load File");

        jButtonBrowse1.setText("Browse");
        jButtonBrowse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowse1ActionPerformed(evt);
            }
        });

        jMenuFile1.setText("File");
        jMenuBar1.add(jMenuFile1);

        jMenuEdit1.setText("Edit");
        jMenuEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEdit1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuEdit1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelnamaApps, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelUAS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxUAS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelUTS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxUTS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label1Hitung1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTugas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addComponent(jComboBoxTugas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonStatistic)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonekspor1)
                        .addGap(40, 40, 40))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButtonBrowse1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelnamaApps)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLoad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBrowse1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1Hitung1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonStatistic)
                        .addComponent(jButtonekspor1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTugas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTugas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUTS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxUTS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelUAS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxUAS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label1Hitung1.getAccessibleContext().setAccessibleName("");
        labelUTS1.getAccessibleContext().setAccessibleName("Presentasi UTS");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBrowse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowse1ActionPerformed
        


  
    }//GEN-LAST:event_jButtonBrowse1ActionPerformed

    private void jMenuEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEdit1ActionPerformed
        String jMenuEdit;
        
        
        jMenuEdit1.setText("Gugun Gunawan");
        System.out.println("About Apliaction");
        System.out.println("Created By");
        System.out.println("Gugun Gunawan       : 1842413");
        System.out.println("Luthfi Imam Maulana : 1841414");
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuEdit1ActionPerformed

    public JButton getjButtonBrowse1() {
        return jButtonBrowse1;
    }

    public void setjButtonBrowse1(JButton jButtonBrowse1) {
        this.jButtonBrowse1 = jButtonBrowse1;
    }

    public JButton getjButtonStatistic() {
        return jButtonStatistic;
    }

    public void setjButtonStatistic(JButton jButtonStatistic) {
        this.jButtonStatistic = jButtonStatistic;
    }

    public JButton getjButtonekspor1() {
        return jButtonekspor1;
    }

    public void setjButtonekspor1(JButton jButtonekspor1) {
        this.jButtonekspor1 = jButtonekspor1;
    }

    public JComboBox getjComboBoxTugas1() {
        return jComboBoxTugas1;
    }

    public void setjComboBoxTugas1(JComboBox jComboBoxTugas1) {
        this.jComboBoxTugas1 = jComboBoxTugas1;
    }

    public JComboBox getjComboBoxUAS1() {
        return jComboBoxUAS1;
    }

    public void setjComboBoxUAS1(JComboBox jComboBoxUAS1) {
        this.jComboBoxUAS1 = jComboBoxUAS1;
    }

    public JComboBox getjComboBoxUTS1() {
        return jComboBoxUTS1;
    }

    public void setjComboBoxUTS1(JComboBox jComboBoxUTS1) {
        this.jComboBoxUTS1 = jComboBoxUTS1;
    }

    public JLabel getjLabelnamaApps() {
        return jLabelnamaApps;
    }

    public void setjLabelnamaApps(JLabel jLabelnamaApps) {
        this.jLabelnamaApps = jLabelnamaApps;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenu getjMenuEdit1() {
        return jMenuEdit1;
    }

    public void setjMenuEdit1(JMenu jMenuEdit1) {
        this.jMenuEdit1 = jMenuEdit1;
    }

    public JMenu getjMenuFile1() {
        return jMenuFile1;
    }

    public void setjMenuFile1(JMenu jMenuFile1) {
        this.jMenuFile1 = jMenuFile1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getjTableInput1() {
        return jTableInput1;
    }

    public void setjTableInput1(JTable jTableInput1) {
        this.jTableInput1 = jTableInput1;
    }

    public JTextField getjTextFieldLoad() {
        return jTextFieldLoad;
    }

    public void setjTextFieldLoad(JTextField jTextFieldLoad) {
        this.jTextFieldLoad = jTextFieldLoad;
    }

    public Label getLabel1Hitung1() {
        return label1Hitung1;
    }

    public void setLabel1Hitung1(Label label1Hitung1) {
        this.label1Hitung1 = label1Hitung1;
    }

    public Label getLabelTugas1() {
        return labelTugas1;
    }

    public void setLabelTugas1(Label labelTugas1) {
        this.labelTugas1 = labelTugas1;
    }

    public Label getLabelUAS1() {
        return labelUAS1;
    }

    public void setLabelUAS1(Label labelUAS1) {
        this.labelUAS1 = labelUAS1;
    }

    public Label getLabelUTS1() {
        return labelUTS1;
    }

    public void setLabelUTS1(Label labelUTS1) {
        this.labelUTS1 = labelUTS1;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormNilaiSTMIK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormNilaiSTMIK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormNilaiSTMIK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormNilaiSTMIK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormNilaiSTMIK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBrowse1;
    private javax.swing.JButton jButtonStatistic;
    private javax.swing.JButton jButtonekspor1;
    private javax.swing.JComboBox jComboBoxTugas1;
    private javax.swing.JComboBox jComboBoxUAS1;
    private javax.swing.JComboBox jComboBoxUTS1;
    private javax.swing.JLabel jLabelnamaApps;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit1;
    private javax.swing.JMenu jMenuFile1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableInput1;
    private javax.swing.JTextField jTextFieldLoad;
    private java.awt.Label label1Hitung1;
    private java.awt.Label labelTugas1;
    private java.awt.Label labelUAS1;
    private java.awt.Label labelUTS1;
    // End of variables declaration//GEN-END:variables
}
